<a href="https://colab.research.google.com/github/BhuvanHande/ML-Lab/blob/main/ML%20lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import numpy as np
import pandas as pd
a=np.array([10,20,30,40])
print(a)

b=np.arange(1,11)
print(b)

for i in range (10,0,-1):
  print(i)

[10 20 30 40]
[ 1  2  3  4  5  6  7  8  9 10]
10
9
8
7
6
5
4
3
2
1

In [29]:
a = np.array([[1,2],
            [3,4]])
b = np.array([[2,4],
            [6,8]])
print(a*b)
print(a-b)

[[ 2  8]
 [18 32]]
[[-1 -2]
 [-3 -4]]

In [19]:
marks=np.array([70,65,50,75])
print(np.mean(marks))
print(np.max(marks))

65.0
75

In [39]:
b = np.array(
[
    [pd.Timestamp('2026-07-22 13:30:00'), 27.5],
    [pd.Timestamp('2026-07-22 15:30:00'), 25.0],
    [pd.Timestamp('2026-07-22 17:30:00'), 23.3],
    [pd.Timestamp('2026-07-23 13:30:00'), 29.0],
    [pd.Timestamp('2026-07-23 15:30:00'), 29.1],
    [pd.Timestamp('2026-07-23 17:30:00'), 27.8],
    [pd.Timestamp('2026-07-24 13:30:00'), 29.3],
    [pd.Timestamp('2026-07-24 15:30:00'), 28.5],
    [pd.Timestamp('2026-07-24 17:30:00'), 24.6],
    [pd.Timestamp('2026-07-25 13:30:00'), 29.5],
    [pd.Timestamp('2026-07-25 15:30:00'), 30.0],
    [pd.Timestamp('2026-07-25 17:30:00'), 25.7],
    [pd.Timestamp('2026-07-26 13:30:00'), 28.5],
    [pd.Timestamp('2026-07-26 15:30:00'), 28.6],
    [pd.Timestamp('2026-07-26 17:30:00'), 26.9],
    [pd.Timestamp('2026-07-27 13:30:00'), 28.0],
    [pd.Timestamp('2026-07-27 15:30:00'), 27.0],
    [pd.Timestamp('2026-07-27 17:30:00'), 24.3],
    [pd.Timestamp('2026-07-28 13:30:00'), 29.0],
    [pd.Timestamp('2026-07-28 15:30:00'), 28.8],
    [pd.Timestamp('2026-07-28 17:30:00'), 27.4]
])

In [43]:
import pandas as pd
stdent={
    "Name":["A","B","C","D"],
    "age ":["12","13","14","15"]
    }
student=pd.DataFrame(stdent)
print(student)

  Name age
0    A   12
1    B   13
2    C   14
3    D   15

In [46]:
from sklearn.datasets import load_iris
iris= load_iris(as_frame=True)
display(iris.frame.head(10))

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
5,5.4,3.9,1.7,0.4,0
6,4.6,3.4,1.4,0.3,0
7,5.0,3.4,1.5,0.2,0
8,4.4,2.9,1.4,0.2,0
9,4.9,3.1,1.5,0.1,0

In [45]:
display(iris.frame.tail())

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2